import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import AuthNav from '@/components/auth-nav/AuthNav';
import { Separator } from '@/components/ui/separator';
import Provider from './_trpc/Provider';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Ve2Max Assessment',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col h-screen">
          <div className="flex flex-1">
            <aside className="w-40 lg:w-56 bg-gray-800 text-white px-8 py-12 space-y-8">
              <Link href={'/'} className="text-2xl font-bold mb-8">
                GFilippos (Guide)
              </Link>
              <nav className="flex flex-col space-y-4">
                <Link href="/users">Users List</Link>
                <AuthNav />
                <Separator />
                <Link href="https://www.gfdevo.com" target="_blank" rel="noopener noreferrer">
                  My portfolio website
                </Link>
                <Link href="https://github.com/GFilippos" target="_blank" rel="noopener noreferrer">
                  My Github page
                </Link>
                <a href="/fg_resume.pdf" target="_blank" rel="noopener noreferrer">
                  My resume
                </a>
              </nav>
            </aside>
            <main className="h-full flex flex-1">
              <Provider>{children}</Provider>
            </main>
          </div>
          <footer className="flex justify-end h-16 gap-4 p-4 bg-gray-100 border-t-2 border-t-primary text-primary">
            <div className="text-center">
              <p>&copy; {new Date().getFullYear()} Ve2Max Users App. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
